gameshop.WebApplication/Controllers/GameController.cs
using gameshop.WebApplication.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;

namespace gameshop.WebApplication.Controllers
{
    public class GameController : Controller
    {
        public IConfiguration Configuration;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly JWTOKEN TokenService;
        public GameController(IConfiguration configuration, JWTOKEN _token, UserManager<IdentityUser> userManager)
        {
            Configuration = configuration;
            TokenService = _token;
            _userManager = userManager;
        }

        public ContentResult GetHostUrl()
        {
            var r = Configuration["RestApiUrl:HostUrl"];
            return Content(r);
        }

        private string CN()
        {
            return ControllerContext.RouteData.Values["controller"].ToString();
        }
        public async Task<IActionResult> Index()
        {
            string _restpath = GetHostUrl().Content + CN();

            var token = TokenService.GenerateJSONWebToken();
            List<GameVM> list = new List<GameVM>();

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Clear();
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                System.Diagnostics.Debug.WriteLine(httpClient.DefaultRequestHeaders);
                using (var response = await httpClient.GetAsync(_restpath))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    list = JsonConvert.DeserializeObject<List<GameVM>>(apiResponse);

                    System.Diagnostics.Debug.WriteLine(response.StatusCode);
                }
            }

            return View(list);
        }

        public async Task<IActionResult> GameFilter(int PlatformID, int CategoryID)
        {
            string _restpath = GetHostUrl().Content + CN();

            var token = TokenService.GenerateJSONWebToken();
            List<GameVM> list = new List<GameVM>();

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Clear();
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                System.Diagnostics.Debug.WriteLine(httpClient.DefaultRequestHeaders);
                using (var response = await httpClient.GetAsync($"{_restpath}?plat={PlatformID}&cat={CategoryID}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    list = JsonConvert.DeserializeObject<List<GameVM>>(apiResponse);

                    System.Diagnostics.Debug.WriteLine(response.StatusCode);
                }
            }

            return View(list);
        }

        public async Task<IActionResult> Edit(int id)
        {
            string _restpath = GetHostUrl().Content + CN();
            var token = TokenService.GenerateJSONWebToken();

            GameVM ob = new GameVM();

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Clear();
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    ob = JsonConvert.DeserializeObject<GameVM>(apiResponse);
                }
            }

            List<PlatformVM> platforms = await StaticPublicRequests.GetPlatforms();
            List<CategoryVM> categories = await StaticPublicRequests.GetCategories();
            List<CompanyVM> publishers = await StaticPublicRequests.GetPublishers();
            List<CompanyVM> developers = await StaticPublicRequests.GetDevelopers();
            ViewBag.Platforms = platforms;
            ViewBag.Categories = categories;
            ViewBag.Publishers = publishers;
            ViewBag.Developers = developers;
            return View(ob);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(GameVM o)
        {
            string _restpath = GetHostUrl().Content + CN();
            var token = TokenService.GenerateJSONWebToken();

            GameVM ob = new GameVM();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Clear();
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                    string jsonString = System.Text.Json.JsonSerializer.Serialize(o);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PutAsync($"{_restpath}/{o.Id}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                        ob = JsonConvert.DeserializeObject<GameVM>(apiResponse);
                    }
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(ex.Message);
            }


            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int id)
        {
            string _restpath = GetHostUrl().Content + CN();
            var token = TokenService.GenerateJSONWebToken();

            GameVM ob = new GameVM();

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Clear();
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    ob = JsonConvert.DeserializeObject<GameVM>(apiResponse);
                }
            }
            List<PlatformVM> platforms = await StaticPublicRequests.GetPlatforms();
            ViewBag.Platforms = platforms;
            List < GameByPlat > gbp = await GetGames(id);
            ViewBag.GamesByPlat = gbp;
            return View(ob);
        }

        public async Task<IActionResult> DetailsShop(int id)
        {
            string _restpath = GetHostUrl().Content + CN();
            var token = TokenService.GenerateJSONWebToken();

            GameVM ob = new GameVM();

            using (var httpClient = new HttpClient())
            {
                httpClient.DefaultRequestHeaders.Clear();
                httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                using (var response = await httpClient.GetAsync($"{_restpath}/{id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    ob = JsonConvert.DeserializeObject<GameVM>(apiResponse);
                }
            }
            List<PlatformVM> platforms = await StaticPublicRequests.GetPlatforms();
            ViewBag.Platforms = platforms;
            List<GameByPlat> gbp = await GetGames(id);
            ViewBag.GamesByPlat = gbp;
            ViewBag.Test = "????";
            foreach (GameByPlat g in gbp) Console.WriteLine(g.PlatformID);
            foreach (PlatformVM g in platforms) Console.WriteLine(g.Id);
            return View(ob);
        }

        public async Task<IActionResult> BuyGame(GameByPlat o, int amount)
        {
            string _restpath = GetHostUrl().Content + "Cart/AddToCart";
            var token = TokenService.GenerateJSONWebToken();

            try
            {
                var user = await _userManager.GetUserAsync(User);
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Clear();
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

                    BuyGame ob = new BuyGame()
                    {
                        amount = amount,
                        GameID = o.Id,
                        UserID = user.Id
                    };

                    string jsonString = System.Text.Json.JsonSerializer.Serialize(ob);
                    var content = new StringContent(jsonString, Encoding.UTF8, "application/json");
                    using (var response = await httpClient.PostAsync($"{_restpath}", content))
                    {
                        string apiResponse = await response.Content.ReadAsStringAsync();
                    }
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(_restpath);
                System.Diagnostics.Debug.WriteLine(ex.Message);
            }

            return RedirectToAction("DetailsShop", new { id = o.GameID });
        }

        public async Task<IActionResult> Delete(int id)
        {
            string _restpath = GetHostUrl().Content + CN();
            var token = TokenService.GenerateJSONWebToken();

            try
            {
                using (var httpClient = new HttpClient())
                {
                    httpClient.DefaultRequestHeaders.Clear();
                    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

gameshop.WebApplication/Views/Partial/GameByPlatBuying.cshtml
@model gameshop.WebApplication.Models.GameByPlat
<div>
    <div class="image" data-title="No"><img src="@ViewData["PlatformImage"]" alt="@ViewData["PlatformName"]"></div>
    <div class="product-des" data-title="Description">
        <p class="product-name">@ViewData["PlatformName"]</p>
        <p class="product-des">@ViewData["GameName"]</p>
    </div>
    <div class="price" data-title="Price"><span>@(Model.AmountEnable - Model.AmountReserved)</span></div>
    <form asp-controller="Game" asp-action="BuyGame">
        <div class="qty" data-title="Qty">
            <input hidden="hidden" asp-for="Id" value="@Model.Id" />
            <input hidden="hidden" asp-for="GameID" value="@Model.GameID" />
            <div class="input-group">
                <!--
                <div class="button minus">
                    <button type="button" class="btn btn-primary btn-number" disabled="disabled" data-type="minus" data-field="amount">
                        <i class="ti-minus"></i>
                    </button>
                </div>
                -->
                <input type="number" id="@Model.Id" name="amount" class="input-number" data-min="1" data-max="100" value="1">
                <!--
                <div class="button plus">
                    <button type="button" class="btn btn-primary btn-number" data-type="plus" data-field="amount">
                        <i class="ti-plus"></i>
                    </button>
                </div>
                -->
            </div>
        </div>
        <div class="action" data-title="Remove">
            <input type="submit" value="ADD TO CART" class="btn btn-primary"/>
        </div>
    </form>
</div>

gameshop.WebApplication/Views/Partial/SingleGameBanner.cshtml
@model gameshop.WebApplication.Models.GameVM
@using gameshop.WebApplication.Controllers;

<div class="col-xl-3 col-lg-4 col-md-4 col-12">
    <div class="single-product">
        <div class="product-img">
            <a href="product-details.html">
                <img class="default-img" src="@Model.ImageURL" alt="#">
                <img class="hover-img" src="@Model.ImageURL" alt="#">
            </a>
            <div class="button-head">
                <div class="product-action">
                    <a data-toggle="modal" data-target="#exampleModal" title="Quick View" href="#"><i class=" ti-eye"></i><span>Quick Shop</span></a>
                    <a title="Wishlist" href="#"><i class=" ti-heart "></i><span>Add to Wishlist</span></a>
                    <a title="Compare" href="#"><i class="ti-bar-chart-alt"></i><span>Add to Compare</span></a>
                </div>
                <div class="product-action-2">
                    <a title="Add to cart" href="#">Add to cart</a>
                </div>
            </div>
        </div>
        <div class="product-content">
            <h3>
                <a asp-area="" asp-controller="Game" asp-action="DetailsShop" asp-route-id="@Model.Id">@Model.Name</a>
            </h3>
            <div class="product-price">
                <span>@ViewData["Category"]</span>
            </div>
        </div>
    </div>
</div>

gameshop.WebApplication/Views/Partial/SingleGameMainBanner.cshtml
@model gameshop.WebApplication.Models.GameVM

<div class="col-lg-4 col-md-6 col-12">
    <div class="single-banner">
        <img src="https://via.placeholder.com/600x370" alt="#">
        <div class="content">
            <p>@ViewData["Category"]</p>
            <h3>
                @Model.Name<br />
                @ViewData["Developer"]<br />
                <!--@ViewData["Publisher"]-->
            </h3>
            <a asp-area="" asp-controller="Game" asp-action="DetailsShop" asp-route-id="@Model.Id">Discover Now</a>
        </div>
    </div>
</div>